package com.feilong.test.webservice.cxf.client.nike;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-04-28T18:44:13.311+08:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://www.nikestore.com.cn/webService", name = "ExpressDeliveryService")
@XmlSeeAlso({ObjectFactory.class})
public interface ExpressDeliveryService {

    @WebResult(name = "returnInfo", targetNamespace = "")
    @RequestWrapper(localName = "transferOrderSign", targetNamespace = "http://www.nikestore.com.cn/webService", className = "com.feilong.test.webservice.cxf.client.nike.TransferOrderSign")
    @WebMethod
    @ResponseWrapper(localName = "transferOrderSignResponse", targetNamespace = "http://www.nikestore.com.cn/webService", className = "com.feilong.test.webservice.cxf.client.nike.TransferOrderSignResponse")
    public java.lang.String transferOrderSign(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
