/*
 * Copyright (C) 2008 feilong (venusdrogon@163.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.feilong.commons.security.oneway;

import junit.framework.Assert;

import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.feilong.commons.core.enumeration.CharsetType;
import com.feilong.commons.core.util.StringUtil;
import com.feilong.commons.security.BaseSecurityTest;
import com.feilong.commons.security.oneway.SHA1Util;

/**
 * The Class SHA1UtilTest.
 * 
 * @author <a href="mailto:venusdrogon@163.com">金鑫</a>
 * @version 1.0 2011-2-7 上午01:12:36
 */
@SuppressWarnings("all")
public class SHA1UtilTest extends BaseSecurityTest{

	/** The Constant log. */
	private static final Logger	log	= LoggerFactory.getLogger(SHA1UtilTest.class);

	/**
	 * {@link com.feilong.commons.security.oneway.MD5Util#encodeFile(java.lang.String)} 的测试方法。
	 */
	@Test
	public void encodeFile(){
		log.debug(SHA1Util.encodeFile("E:\\DataCommon\\Java\\JDK API 1.6.0 中文版.CHM"));
	}

	/**
	 * Encode.
	 */
	@Test
	public void encode(){
		// Assert.assertEquals("bbed833d2c7805c4bf039b140bec7e7452125a04efa9e0b296395a9b95c2d44c", SHAUtil.encode("passwordhunter"));
		byte[] bytes = StringUtil.toBytes("你好", CharsetType.UTF8);
		Assert.assertEquals("440ee0853ad1e99f962b63e459ef992d7c211722", SHA1Util.encode(bytes));
	}

	/**
	 * Encode1.
	 */
	@Test
	public void encode1(){
		log.debug(debugSecurityValue(SHA1Util.encode("521000")));
		log.debug(debugSecurityValue(SHA1Util.encode("2" + "5000" + "200000" + "nikejdistore")));
		String origin = "sdadadadadaadasasdasdadas"
				+ "dasdadasdadadasdasdasdadasdasdadadadadasdadadadad"
				+ "aaadasdasdasdasdadadadadaadasasdasdadasdasda"
				+ "dasdadadasdasdasdadas"
				+ "dasdadadadadasdadadadadaaadasdasdasdasasda"
				+ "sdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaa"
				+ "dasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdada"
				+ "dadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadasaddssadsaadasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadasaddssadsaadasdasdasdasdasdasdasdadasaddssadsaadasdasdasdasdasdasdadasaddssadsaadsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadasaddssadsaadasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaad"
				+ "dadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadasaddssadsaadasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadasaddssadsaadasdasdasdasdasdasdasdadasaddssadsaadasdasdasdasdasdasdadasaddssadsaadsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadasaddssadsaadasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaad"
				+ "dadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadasaddssadsaadasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadasaddssadsaadasdasdasdasdasdasdasdadasaddssadsaadasdasdasdasdasdasdadasaddssadsaadsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadasaddssadsaadasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaad"
				+ "dadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadasaddssadsaadasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadasaddssadsaadasdasdasdasdasdasdasdadasaddssadsaadasdasdasdasdasdasdadasaddssadsaadsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadasaddssadsaadasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaad"
				+ "dadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadasaddssadsaadasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadasaddssadsaadasdasdasdasdasdasdasdadasaddssadsaadasdasdasdasdasdasdadasaddssadsaadsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadasaddssadsaadasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaad"
				+ "dadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadasaddssadsaadasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadasaddssadsaadasdasdasdasdasdasdasdadasaddssadsaadasdasdasdasdasdasdadasaddssadsaadsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadasaddssadsaadasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasasdasdasdasdasdasdasdasdadasaddssadsaadsasdsdadadadadaadasasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasdadadadadaad"
				+ "asasdasdadasdasdadasdadadasdasdasdadasdasdadadadadasdadadadadaaadasdasdasdasa"
				+ "sdasdasdasdasdasdasdasdadasaddssadsaadsasdasdasdasdasdasdasdasdadas"
				+ "addssadsaadasdasdasdasaddssadsaadasdasdasdasdasdasdasdadasaddssadsaadasdasdasdaaddssadsaadasdasdasdasdasdasdasdadasaddssadsaadasdasdasdaaddssadsaadasdasdasdasdasdasdasdadasaddssadsaadasdasdasdaaddssadsaadasdasdasdasdasdasdasdadasaddssadsaadasdasdasdaaddssadsaadasdasdasdasdasdasdasdadasaddssadsaadasdasdasdaaddssadsaadasdasdasdasdasdasdasdadasaddssadsaadasdasdasdaaddssadsaadasdasdasdasdasdasdasdadasaddssadsaadasdasdasdadasdasdasdadasaddssadsaadasdasdasda"
				+ "sdasdasdadasaddssadsaad";
		log.debug(debugSecurityValue(SHA1Util.encode(origin)));
	}

}
