
/*
 * 
 */

package com.feilong.test.webservice.cxf.client.nike;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-04-28T18:44:13.378+08:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "ExpressDeliveryServiceService", 
                  wsdlLocation = "http://192.168.2.236:8001/nikestore/cxf/expressDeliveryService?wsdl",
                  targetNamespace = "http://www.nikestore.com.cn/webService") 
public class ExpressDeliveryServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.nikestore.com.cn/webService", "ExpressDeliveryServiceService");
    public final static QName ExpressDeliveryServicePort = new QName("http://www.nikestore.com.cn/webService", "ExpressDeliveryServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.2.236:8001/nikestore/cxf/expressDeliveryService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ExpressDeliveryServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.2.236:8001/nikestore/cxf/expressDeliveryService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ExpressDeliveryServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ExpressDeliveryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExpressDeliveryServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns ExpressDeliveryService
     */
    @WebEndpoint(name = "ExpressDeliveryServicePort")
    public ExpressDeliveryService getExpressDeliveryServicePort() {
        return super.getPort(ExpressDeliveryServicePort, ExpressDeliveryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExpressDeliveryService
     */
    @WebEndpoint(name = "ExpressDeliveryServicePort")
    public ExpressDeliveryService getExpressDeliveryServicePort(WebServiceFeature... features) {
        return super.getPort(ExpressDeliveryServicePort, ExpressDeliveryService.class, features);
    }

}
