/* Generated By:JavaCC: Do not edit this line. TagExportParserConstants.java */
package com.feilong.taglib.pager.parser;

@SuppressWarnings("all")public interface TagExportParserConstants{

	int			EOF					= 0;

	int			EQUALS				= 6;

	int			COMMA				= 7;

	int			SEMICOLON			= 8;

	int			PAGER_NUMBER		= 9;

	int			PAGER_OFFSET		= 10;

	int			PAGER_PAGE			= 11;

	int			PAGER_PAGENUMBER	= 12;

	int			PAGER_PAGEOFFSET	= 13;

	int			INDEX_ITEMCOUNT		= 14;

	int			INDEX_ITEMS			= 15;

	int			INDEX_PAGECOUNT		= 16;

	int			INDEX_PAGES			= 17;

	int			PAGE_FIRST			= 18;

	int			PAGE_FIRSTITEM		= 19;

	int			PAGE_LAST			= 20;

	int			PAGE_LASTITEM		= 21;

	int			PAGE_NUMBER			= 22;

	int			PAGE_PAGE			= 23;

	int			PAGE_PAGENUMBER		= 24;

	int			PAGE_PAGEURL		= 25;

	int			PAGE_URL			= 26;

	int			IDENTIFIER			= 27;

	int			LETTER				= 28;

	int			DIGIT				= 29;

	int			DEFAULT				= 0;

	int			PAGER_STATE			= 1;

	int			INDEX_STATE			= 2;

	int			PAGE_STATE			= 3;

	String[]	tokenImage			= {
			"<EOF>",
			"\" \"",
			"\"\\t\"",
			"\"\\n\"",
			"\"\\r\"",
			"\"\\f\"",
			"\"=\"",
			"\",\"",
			"\";\"",
			"\"number\"",
			"\"offset\"",
			"\"page\"",
			"\"pageNumber\"",
			"\"pageOffset\"",
			"\"itemCount\"",
			"\"items\"",
			"\"pageCount\"",
			"\"pages\"",
			"\"first\"",
			"\"firstItem\"",
			"\"last\"",
			"\"lastItem\"",
			"\"number\"",
			"\"page\"",
			"\"pageNumber\"",
			"\"pageUrl\"",
			"\"url\"",
			"<IDENTIFIER>",
			"<LETTER>",
			"<DIGIT>",				};
}
